//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorClient.MortgageServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loan", Namespace="http://schemas.datacontract.org/2004/07/MortgageCalculatorWCFService")]
    [System.SerializableAttribute()]
    public partial class Loan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InterestRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TermField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InterestRate {
            get {
                return this.InterestRateField;
            }
            set {
                if ((this.InterestRateField.Equals(value) != true)) {
                    this.InterestRateField = value;
                    this.RaisePropertyChanged("InterestRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LoanAmount {
            get {
                return this.LoanAmountField;
            }
            set {
                if ((this.LoanAmountField.Equals(value) != true)) {
                    this.LoanAmountField = value;
                    this.RaisePropertyChanged("LoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Term {
            get {
                return this.TermField;
            }
            set {
                if ((this.TermField.Equals(value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MortgageServiceReference.IMortgageCalculator")]
    public interface IMortgageCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMortgageCalculator/getMonthlyPayment", ReplyAction="http://tempuri.org/IMortgageCalculator/getMonthlyPaymentResponse")]
        double getMonthlyPayment(CalculatorClient.MortgageServiceReference.Loan loan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMortgageCalculator/getMonthlyPayment", ReplyAction="http://tempuri.org/IMortgageCalculator/getMonthlyPaymentResponse")]
        System.Threading.Tasks.Task<double> getMonthlyPaymentAsync(CalculatorClient.MortgageServiceReference.Loan loan);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMortgageCalculatorChannel : CalculatorClient.MortgageServiceReference.IMortgageCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MortgageCalculatorClient : System.ServiceModel.ClientBase<CalculatorClient.MortgageServiceReference.IMortgageCalculator>, CalculatorClient.MortgageServiceReference.IMortgageCalculator {
        
        public MortgageCalculatorClient() {
        }
        
        public MortgageCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MortgageCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MortgageCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MortgageCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getMonthlyPayment(CalculatorClient.MortgageServiceReference.Loan loan) {
            return base.Channel.getMonthlyPayment(loan);
        }
        
        public System.Threading.Tasks.Task<double> getMonthlyPaymentAsync(CalculatorClient.MortgageServiceReference.Loan loan) {
            return base.Channel.getMonthlyPaymentAsync(loan);
        }
    }
}
