//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TafesaClient.EnrolmentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enrolment", Namespace="http://schemas.datacontract.org/2004/07/Assignment614.Classes")]
    [System.SerializableAttribute()]
    public partial class Enrolment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateEnrolledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateEnrolled {
            get {
                return this.DateEnrolledField;
            }
            set {
                if ((this.DateEnrolledField.Equals(value) != true)) {
                    this.DateEnrolledField = value;
                    this.RaisePropertyChanged("DateEnrolled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((this.StudentIDField.Equals(value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnrolmentServiceReference.IStudentEnrolment")]
    public interface IStudentEnrolment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentEnrolment/AddEnrolment", ReplyAction="http://tempuri.org/IStudentEnrolment/AddEnrolmentResponse")]
        void AddEnrolment(int studentID, int courseID, System.DateTime dateEnrolled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentEnrolment/AddEnrolment", ReplyAction="http://tempuri.org/IStudentEnrolment/AddEnrolmentResponse")]
        System.Threading.Tasks.Task AddEnrolmentAsync(int studentID, int courseID, System.DateTime dateEnrolled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentEnrolment/GetAllEnrollments", ReplyAction="http://tempuri.org/IStudentEnrolment/GetAllEnrollmentsResponse")]
        TafesaClient.EnrolmentServiceReference.Enrolment[] GetAllEnrollments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentEnrolment/GetAllEnrollments", ReplyAction="http://tempuri.org/IStudentEnrolment/GetAllEnrollmentsResponse")]
        System.Threading.Tasks.Task<TafesaClient.EnrolmentServiceReference.Enrolment[]> GetAllEnrollmentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentEnrolmentChannel : TafesaClient.EnrolmentServiceReference.IStudentEnrolment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentEnrolmentClient : System.ServiceModel.ClientBase<TafesaClient.EnrolmentServiceReference.IStudentEnrolment>, TafesaClient.EnrolmentServiceReference.IStudentEnrolment {
        
        public StudentEnrolmentClient() {
        }
        
        public StudentEnrolmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentEnrolmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentEnrolmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentEnrolmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddEnrolment(int studentID, int courseID, System.DateTime dateEnrolled) {
            base.Channel.AddEnrolment(studentID, courseID, dateEnrolled);
        }
        
        public System.Threading.Tasks.Task AddEnrolmentAsync(int studentID, int courseID, System.DateTime dateEnrolled) {
            return base.Channel.AddEnrolmentAsync(studentID, courseID, dateEnrolled);
        }
        
        public TafesaClient.EnrolmentServiceReference.Enrolment[] GetAllEnrollments() {
            return base.Channel.GetAllEnrollments();
        }
        
        public System.Threading.Tasks.Task<TafesaClient.EnrolmentServiceReference.Enrolment[]> GetAllEnrollmentsAsync() {
            return base.Channel.GetAllEnrollmentsAsync();
        }
    }
}
