//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieClient.MovieServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movies", Namespace="http://schemas.datacontract.org/2004/07/MovieAdminService")]
    [System.SerializableAttribute()]
    public partial class Movies : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Director {
            get {
                return this.DirectorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorField, value) != true)) {
                    this.DirectorField = value;
                    this.RaisePropertyChanged("Director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovieServiceReference.IMovieAdmin")]
    public interface IMovieAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieAdmin/GetMovies", ReplyAction="http://tempuri.org/IMovieAdmin/GetMoviesResponse")]
        MovieClient.MovieServiceReference.Movies[] GetMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieAdmin/GetMovies", ReplyAction="http://tempuri.org/IMovieAdmin/GetMoviesResponse")]
        System.Threading.Tasks.Task<MovieClient.MovieServiceReference.Movies[]> GetMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieAdmin/GetAMovie", ReplyAction="http://tempuri.org/IMovieAdmin/GetAMovieResponse")]
        MovieClient.MovieServiceReference.Movies GetAMovie(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieAdmin/GetAMovie", ReplyAction="http://tempuri.org/IMovieAdmin/GetAMovieResponse")]
        System.Threading.Tasks.Task<MovieClient.MovieServiceReference.Movies> GetAMovieAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieAdmin/addMovie", ReplyAction="http://tempuri.org/IMovieAdmin/addMovieResponse")]
        void addMovie(string title, string Director, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieAdmin/addMovie", ReplyAction="http://tempuri.org/IMovieAdmin/addMovieResponse")]
        System.Threading.Tasks.Task addMovieAsync(string title, string Director, System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovieAdminChannel : MovieClient.MovieServiceReference.IMovieAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieAdminClient : System.ServiceModel.ClientBase<MovieClient.MovieServiceReference.IMovieAdmin>, MovieClient.MovieServiceReference.IMovieAdmin {
        
        public MovieAdminClient() {
        }
        
        public MovieAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MovieClient.MovieServiceReference.Movies[] GetMovies() {
            return base.Channel.GetMovies();
        }
        
        public System.Threading.Tasks.Task<MovieClient.MovieServiceReference.Movies[]> GetMoviesAsync() {
            return base.Channel.GetMoviesAsync();
        }
        
        public MovieClient.MovieServiceReference.Movies GetAMovie(string title) {
            return base.Channel.GetAMovie(title);
        }
        
        public System.Threading.Tasks.Task<MovieClient.MovieServiceReference.Movies> GetAMovieAsync(string title) {
            return base.Channel.GetAMovieAsync(title);
        }
        
        public void addMovie(string title, string Director, System.DateTime date) {
            base.Channel.addMovie(title, Director, date);
        }
        
        public System.Threading.Tasks.Task addMovieAsync(string title, string Director, System.DateTime date) {
            return base.Channel.addMovieAsync(title, Director, date);
        }
    }
}
